version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    restart: always
    stdin_open: true
    volumes:
      - '.:/src'
    tty: true
    depends_on:
      - db
    env_file:
      - .env.local
    entrypoint: ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
  db:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 1521:1521
      - 5500:5500

volumes:
    oracle-data:
